---
all:
  children:
    kubernetes:
      hosts:
        nexaretail-cluster:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/config"
          kube_context: "kind-nexaretail-aks"
